### ISSUE TITLE
About running.... error

### ISSUE THREAD

**Issue by plumsky** [wezu/p3d_auto_deferred_shader#1]
@wezu 
When I run `main.py`, got error below:
```
Known pipe types:
  wglGraphicsPipe
(all display modules loaded.)
:display(warning): FrameBufferProperties available less than requested.
  requested: depth_bits=32 color_bits=3 red_bits=1 green_bits=1 blue_bits=1 alpha_bits=1 back_buffers=1 force_hardware 
  got: depth_bits=24 color_bits=24 red_bits=8 green_bits=8 blue_bits=8 alpha_bits=8 stencil_bits=8 back_buffers=1 force_hardware 

[Done] exited with code=3221225477 in 1.3 seconds 
```

I use python3.6 64 with panda3d 1.10.0-x64 on win10.
Is my hardware not support?

**Comment by wezu** [comment]
Looks like the 32bit depth buffer is the problem. I'll update the code, but for now you can try:
in deferred_render.py line 844 set `props.set_depth_bits(32)` to `props.set_depth_bits(24)` and in main.py line 5 `loadPrcFileData("", "depth-bits 32")` to `loadPrcFileData("", "depth-bits 24")`

**Comment by plumsky** [comment]
@wezu Thanks your reply.
I follow the update but still not work with short message.
```
Known pipe types:
  wglGraphicsPipe
(all display modules loaded.)

[Done] exited with code=3221225477 in 0.841 seconds
```
I can't find other message about this.

**Comment by wezu** [comment]
The error message is not mine, it's not looking as something Python would throw and not in Panda3D style. After a quick google search I think it's a C++ error probably memory access violation. Can you run other panda3d programs? Can you try a newer, dev version of panda3d?

**Comment by plumsky** [comment]
Yes, I can run other panda3d programs like `https://github.com/wezu/Avolition` or `https://github.com/wezu/p3d_gpu_particle`. 
I use shell to run code and find more error info:
```
Known pipe types:
  wglGraphicsPipe
(all display modules loaded.)
Traceback (most recent call last):
  File "C:\Users\ps\Downloads\p3d_auto_deferred_shader-master\main.py", line 62, in <module>
    d=Demo()
  File "C:\Users\ps\Downloads\p3d_auto_deferred_shader-master\main.py", line 29, in __init__
    DeferredRenderer(**options.get())
  File "C:\Users\ps\Downloads\p3d_auto_deferred_shader-master\deferred_render.py", line 102, in __init__
    if 'name' in self.filter_stages[-1]:
IndexError: list index out of range
Assertion failed: _pipe == (GraphicsPipe *)NULL at line 190 of c:\buildslave\sdk-windows-amd64\build\panda\src\display\graphicsOutput.cxx
Assertion failed: _window == (GraphicsOutput *)NULL at line 78 of c:\buildslave\sdk-windows-amd64\build\panda\src\display\displayRegion.cxx
Assertion failed: _window == (GraphicsOutput *)NULL at line 78 of c:\buildslave\sdk-windows-amd64\build\panda\src\display\displayRegion.cxx
Assertion failed: _pipe == (GraphicsPipe *)NULL at line 190 of c:\buildslave\sdk-windows-amd64\build\panda\src\display\graphicsOutput.cxx
Assertion failed: _window == (GraphicsOutput *)NULL at line 78 of c:\buildslave\sdk-windows-amd64\build\panda\src\display\displayRegion.cxx
Assertion failed: _window == (GraphicsOutput *)NULL at line 78 of c:\buildslave\sdk-windows-amd64\build\panda\src\display\displayRegion.cxx
Assertion failed: _pipe == (GraphicsPipe *)NULL at line 190 of c:\buildslave\sdk-windows-amd64\build\panda\src\display\graphicsOutput.cxx
Assertion failed: _window == (GraphicsOutput *)NULL at line 78 of c:\buildslave\sdk-windows-amd64\build\panda\src\display\displayRegion.cxx
Assertion failed: _window == (GraphicsOutput *)NULL at line 78 of c:\buildslave\sdk-windows-amd64\build\panda\src\display\displayRegion.cxx
```
Then I debug code, find `self.filter_stages` is empty list. I check `options.get()` the value is `{'filter_setup': [], 'shading_setup': {}, 'shadows': 256}`, it's seem not read any data from `full.ini`.

**Comment by wezu** [comment]
I've tested it on windows 10 x64 both python 2.7 and python 3.6 and I can't reproduce it. I've changed the code to print errors reading the ini file, but I don't think that's the problem (it would return None, None not a empty list and dict). Anyway the reading confing from an ini file part is not the important thing in the project, you can just store the config as a dict, and that's what I did. If all else fails comment out `DeferredRenderer(**options.get())` and use `DeferredRenderer(**config_full)`
